=== Simicart/bianca-nera/app/code/Vnecoms/PageBuilder/etc/vcms_section_include.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="include" type="includeDeclaration"/>

    <xs:complexType name="includeDeclaration">
        <xs:sequence>
        	<xs:choice minOccurs="1" maxOccurs="1">
        		<xs:element ref="section" />
        	</xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:attributeGroup name="sectionAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
    </xs:attributeGroup>

	<xs:attributeGroup name="elementAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
        <xs:attribute name="sortOrder" type="xs:float" use="optional" />
    </xs:attributeGroup>
    
    <xs:attributeGroup name="fieldAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
    </xs:attributeGroup>
   
    
    <xs:element name="section">
        <xs:annotation>
            <xs:documentation>
                Section Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                	<xs:element name="type" type="xs:string" />
                    <xs:element name="template" type="xs:string" />
                    <xs:element name="component" type="xs:string" />
                    <xs:element name="preview_height" type="xs:string" />
                    <xs:element name="class" type="xs:string" />
                    <xs:element name="block_template" type="xs:string"/>
                    <xs:element ref="fields" />
                </xs:choice>
            </xs:sequence>

            <xs:attributeGroup ref="sectionAttributeGroup"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="fields">
        <xs:annotation>
            <xs:documentation>
                Fields Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                	<xs:element ref="element" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="element">
        <xs:annotation>
            <xs:documentation>
                Element Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                	<xs:element name="label" type="xs:string" />
                	<xs:element name="type" type="xs:string" />
                	<xs:element name="is_active" type="xs:boolean" />
        			<xs:element ref="data" />
        			<xs:element ref="fields" />
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="elementAttributeGroup"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:annotation>
            <xs:documentation>
                Element Data Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
            	<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="mixedDataType">
        <xs:choice>
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="componentName">
        <xs:annotation>
            <xs:documentation>
                Item id attribute for elements section, widget, field can has only [a-zA-Z0-9/_]. Minimal length 2 symbol. Case sensitive.
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]{1,}" />
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Simicart/bianca-nera/magento/app/code/Vnecoms/PdfPro/etc/pdf_section/pdf_header1.xml
<?xml version="1.0"?>
<include xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_section_include.xsd">
    <!-- Header 1 -->
    <section name="pdf_header1">
        <type>pdf_header</type>
        <template>Vnecoms_PdfPro/section/pdf-header1</template>
        <component>Vnecoms_PageBuilder/js/section/default</component>
        <block_template>Vnecoms_PdfPro::section/pdf-header1.phtml</block_template>
        <preview_height>80px</preview_height>
        <fields>
        	<element name="logo">
           		<label>Logo</label>
           		<type>img</type>
           		<class>Vnecoms\PdfPro\Block\PdfBuilder\Img</class>
           		<data>
           			<imgType>static</imgType> <!-- static, media, url -->
           			<imgFile>Vnecoms_PdfPro/images/vnecoms_logo.png</imgFile>
           		</data>
           		<is_active>1</is_active>
           	</element>
           	<element name="header_text">
                <label>Header Text</label>
                <type>editor</type>
                <is_active>1</is_active>
                <data>                    <code>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque imperdiet purus quis metus.</code>
                    <frontend_class>pdf-header-text</frontend_class>
                </data>
            </element>
        </fields>
    </section>
</include>

=== Simicart/bianca-nera/app/code/Vnecoms/PdfPro/etc/pdf_section/pdf_other-1col.xml
<?xml version="1.0"?>
<include xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_section_include.xsd">
    <!-- Header 1 -->
    <section name="pdf_other_1col">
        <type>pdf_other</type>
        <template>Vnecoms_PdfPro/section/pdf-other-1col</template>
        <component>Vnecoms_PageBuilder/js/section/default</component>
        <block_template>Vnecoms_PdfPro::section/pdf-other-1col.phtml</block_template>
        <preview_height>80px</preview_height>
        <fields>
           	<element name="text">
                <label>Text</label>
                <type>editor</type>
                <is_active>1</is_active>
                <data>
                    <code><![CDATA[<strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.]]></code>
                    <frontend_class>pdf-other-text</frontend_class>
                </data>
            </element>
        </fields>
    </section>
</include>

=== Simicart/bianca-nera/app/code/Vnecoms/PageBuilder/etc/vcms_section/test.xml
<?xml version="1.0"?>
<include xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_section_include.xsd">
    <section name="test">
       	<type>welcome</type>
           <template>Vnecoms_PageBuilder/section/default</template>
           <component>Vnecoms_PageBuilder/js/section/default</component>
           <block_template>Vnecoms_PageBuilder::section/default.phtml</block_template>
           <preview_height>85px</preview_height>
           <fields>
           	<element name="sample_image">
           		<label>Sample Image</label>
           		<type>img</type>
           		<data>
           			<imgType>static</imgType> <!-- static, media, url -->
           			<imgFile>Vnecoms_PageBuilder/images/11_9.jpg</imgFile>
           		</data>
           		<is_active>1</is_active>
           	</element>
		</fields>
	</section>
</include>

=== Simicart/bianca-nera/magento/app/code/Vnecoms/PageBuilder/etc/vcms_section/layout-2column-left.xml
<?xml version="1.0"?>
<include xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_section_include.xsd">
   	<section name="layout_2columns_left">
		<type>layout</type>
		<template>Vnecoms_PageBuilder/section/layout-2columns-left</template>
		<component>Vnecoms_PageBuilder/js/section/layout</component>
		<block_template>Vnecoms_PageBuilder::section/default.phtml</block_template>
		<preview_height>85px</preview_height>
		<fields>
			<element name="left_column">
                <label>Left Column</label>
                <type>container</type>
                <is_active>1</is_active>
                <data>
                    <frontend_class>pb-container-left</frontend_class>
                </data>
                <fields>
                	<element name="image">
		           		<label>Image</label>
		           		<type>img</type>
		           		<data>
		           			<imgType>static</imgType> <!-- static, media, url -->
		           			<imgFile>Vnecoms_PageBuilder/images/500-500.jpg</imgFile>
		           		</data>
		           		<is_active>1</is_active>
		           	</element>
                </fields>
            </element>
			<element name="right_column">
                <label>Right Column</label>
                <type>container</type>
                <is_active>1</is_active>
                <data>
                    <frontend_class>pb-container-right</frontend_class>
                </data>
                <fields>
                	<element name="first_element">
						<label>First Element</label>
						<type>section</type>
						<is_active>1</is_active>
						<data>
							<section_name>feature7</section_name>
						</data>
					</element>
                </fields>
            </element>
		</fields>
	</section>
</include>

=== Simicart/bianca-nera/Store/app/code/Vnecoms/PdfPro/etc/pdf_section/shipment/pdf_items1.xml
<?xml version="1.0"?>
<include xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_section_include.xsd">
    <!-- Items 1 block -->
    <section name="pdf_shipment_items1">
        <type>pdf_shipment_items</type>
        <template>Vnecoms_PdfPro/section/pdf-items1</template>
        <component>Vnecoms_PageBuilder/js/section/default</component>
        <block_template>Vnecoms_PdfPro::section/pdf-items1.phtml</block_template>
        <preview_height>110px</preview_height>
        <fields>
            <element name="items_list">
                <label>Items List</label>
                <type>list</type>
                <is_active>1</is_active>
                <data>
                    <template>Vnecoms_PdfPro/section/pdf-items1/list</template>
                    <block_template>Vnecoms_PdfPro::section/pdf-shipment-items1/list.phtml</block_template>
                    <edit_template>Vnecoms_PageBuilder/field/edit/list</edit_template>
                    <component>Vnecoms_PageBuilder/js/field/list</component>
                    <templateItem>items_col2</templateItem>
                    <canAddNewItem>1</canAddNewItem>
                </data>
                <fields>
                	<element name="items_col1">
                        <label>Items Column</label>
                        <type>group</type>
                        <is_active>1</is_active>
                        <data>
                            <template>Vnecoms_PdfPro/section/pdf-items1/group</template>
                            <block_template>Vnecoms_PdfPro::section/pdf-items1/group.phtml</block_template>
                            <label_element>header_label</label_element>
                            <frontend_class>pdf-items-col</frontend_class>
                            <component>Vnecoms_PdfPro/js/field/group-item</component>
                            <!-- The label of this element will be getting from this child field -->
                        </data>
                        <fields>
                            <element name="header_label">
                                <label>Header Label</label>
                                <type>editor</type>
                                <is_active>1</is_active>
                                <data>
                                    <code>QTY</code>
                                </data>
                            </element>
                            <element name="value">
                                <label>Value</label>
                                <type>editor</type>
                                <is_active>1</is_active>
                                <data>
                                    <code><![CDATA[{{var item.qty}}]]></code>
                                </data>
                            </element>
                        </fields>
                    </element>
                    <element name="items_col2">
                        <label>Items Column</label>
                        <type>group</type>
                        <is_active>1</is_active>
                        <data>
                            <template>Vnecoms_PdfPro/section/pdf-items1/group</template>
                            <block_template>Vnecoms_PdfPro::section/pdf-items1/group.phtml</block_template>
                            <label_element>header_label</label_element>
                            <frontend_class>pdf-items-col</frontend_class>
                            <component>Vnecoms_PdfPro/js/field/group-item</component>
                            <!-- The label of this element will be getting from this child field -->
                        </data>
                        <fields>
                            <element name="header_label">
                                <label>Header Label</label>
                                <type>editor</type>
                                <is_active>1</is_active>
                                <data>
                                    <code>Product</code>
                                </data>
                            </element>
                            <element name="value">
                                <label>Value</label>
                                <type>editor</type>
                                <is_active>1</is_active>
                                <data>
                                    <isCodeEditor>1</isCodeEditor>
                                    <code><![CDATA[{{var item.name}}
{{foreach1 item.options as option}}
	<label>{{var option.label}}</label> :{{var option.value}}<br />
{{/foreach1}}]]></code>
                                </data>
                            </element>
                        </fields>
                    </element>
                    <element name="items_col3">
                        <label>Items Column</label>
                        <type>group</type>
                        <is_active>1</is_active>
                        <data>
                            <template>Vnecoms_PdfPro/section/pdf-items1/group</template>
                            <block_template>Vnecoms_PdfPro::section/pdf-items1/group.phtml</block_template>
                            <label_element>header_label</label_element>
                            <frontend_class>pdf-items-col</frontend_class>
                            <component>Vnecoms_PdfPro/js/field/group-item</component>
                            <!-- The label of this element will be getting from this child field -->
                        </data>
                        <fields>
                            <element name="header_label">
                                <label>Header Label</label>
                                <type>editor</type>
                                <is_active>1</is_active>
                                <data>
                                    <code>Sku</code>
                                </data>
                            </element>
                            <element name="value">
                                <label>Value</label>
                                <type>editor</type>
                                <is_active>1</is_active>
                                <data>
                                    <code><![CDATA[{{var item.sku}}]]></code>
                                </data>
                            </element>
                        </fields>
                    </element>
                </fields>
            </element>
        </fields>
    </section>
</include>

=== Simicart/bianca-nera/magento/app/code/Vnecoms/PdfPro/etc/pdf_section/creditmemo/pdf_totals1.xml
<?xml version="1.0"?>
<include xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_section_include.xsd">
    <!-- Items 1 block -->
    <section name="pdf_creditmemo_totals1">
        <type>pdf_creditmemo_totals</type>
        <template>Vnecoms_PdfPro/section/pdf-totals1</template>
        <component>Vnecoms_PageBuilder/js/section/default</component>
        <block_template>Vnecoms_PdfPro::section/pdf-totals1.phtml</block_template>
        <preview_height>110px</preview_height>
        <fields>
            <element name="totals_block">
                 <label>Totals Block</label>
                 <type>editor</type>
                 <is_active>1</is_active>
                 <data>
					<template>Vnecoms_PdfPro/section/pdf-totals1/totals-block</template>
					<edit_template>Vnecoms_PdfPro/section/pdf-totals1/edit/totals-block</edit_template>
					<block_template>Vnecoms_PdfPro::section/pdf-creditmemo-totals1/totals-block.phtml</block_template>
                    <code>---</code>
                 </data>
             </element>
        </fields>
    </section>
</include>
