=== Simicart/bianca-nera/magento/app/code/Vnecoms/PageBuilder/etc/vcms_section.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config" type="configDeclaration"/>

    <xs:complexType name="configDeclaration">
        <xs:sequence>
        	<xs:choice minOccurs="0" maxOccurs="unbounded">
        		<xs:element ref="sections" />
        		<xs:element ref="types" />
        	</xs:choice>
        </xs:sequence>
    </xs:complexType>
    
	<xs:element name="sections">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="section" />
                    <xs:element name="include" type="includeType"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueSectionName">
            <xs:annotation>
                <xs:documentation>
                    Attribute id is unique under all sections
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="section"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    
    <xs:complexType name="includeType">
        <xs:annotation>
            <xs:documentation>
                Include Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="path" type="typePath" use="required" />
    </xs:complexType>
    
    <xs:simpleType name="typePath">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                    Path identifier. Item can has only [a-zA-Z0-9/_:]. Minimal length 8 symbol. Case sensitive.
                    For example: <Magento_Module>::path/to/file.xml (path in the "etc/adminhtml" area in module)
                 ]]>
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]+[a-zA-Z0-9]{1,}_[A-Z]+[A-Z0-9a-z]{1,}::[A-Za-z_0-9/.]{1,}" />
            <xs:minLength value="8" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="types">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="type" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueTypeName">
            <xs:annotation>
                <xs:documentation>
                    Attribute id is unique under all sections
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="type"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    
    <xs:attributeGroup name="typeAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
        <xs:attribute name="sortOrder" type="xs:float" use="optional" />
    </xs:attributeGroup>
    <xs:attributeGroup name="sectionAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
    </xs:attributeGroup>

	<xs:attributeGroup name="elementAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
        <xs:attribute name="sortOrder" type="xs:float" use="optional" />
    </xs:attributeGroup>
    
    <xs:attributeGroup name="fieldAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
    </xs:attributeGroup>
    
    <xs:element name="type">
        <xs:annotation>
            <xs:documentation>
                Type Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                	<xs:element name="label" type="xs:string" />
                	<xs:element name="resource" type="xs:string" />
                </xs:choice>
            </xs:sequence>

            <xs:attributeGroup ref="typeAttributeGroup"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="section">
        <xs:annotation>
            <xs:documentation>
                Section Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                	<xs:element name="type" type="xs:string" />
                    <xs:element name="template" type="xs:string" />
                    <xs:element name="component" type="xs:string" />
                    <xs:element name="preview_height" type="xs:string" />
                    <xs:element name="class" type="xs:string" />
                    <xs:element name="block_template" type="xs:string"/>
                    <xs:element ref="fields" />
                </xs:choice>
            </xs:sequence>

            <xs:attributeGroup ref="sectionAttributeGroup"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="fields">
        <xs:annotation>
            <xs:documentation>
                Fields Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                	<xs:element ref="element" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="element">
        <xs:annotation>
            <xs:documentation>
                Element Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                	<xs:element name="label" type="xs:string" />
                	<xs:element name="type" type="xs:string" />
                	<xs:element name="class" type="xs:string" />
                	<xs:element name="is_active" type="xs:boolean" />
        			<xs:element ref="data" />
        			<xs:element ref="fields" />
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="elementAttributeGroup"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:annotation>
            <xs:documentation>
                Element Data Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
            	<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="mixedDataType">
        <xs:choice>
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="componentName">
        <xs:annotation>
            <xs:documentation>
                Item id attribute for elements section, widget, field can has only [a-zA-Z0-9/_]. Minimal length 2 symbol. Case sensitive.
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]{1,}" />
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Simicart/bianca-nera/Store/app/code/Vnecoms/PageBuilder/etc/vcms_section.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_section.xsd">
	<types>

		<type name="layout" sortOrder="1">
			<label>Layout</label>
			<resource>page_builder</resource>
		</type>

		<type name="welcome" sortOrder="10">
			<label>Welcome</label>
			<resource>page_builder</resource>
		</type>
		<type name="about" sortOrder="20">
			<label>About</label>
			<resource>page_builder</resource>
		</type>
        <type name="features" sortOrder="30">
            <label><![CDATA[Features & Services]]></label>
            <resource>page_builder</resource>
        </type>
        <type name="faq" sortOrder="30">
            <label>FAQ</label>
            <resource>page_builder</resource>
        </type>
        
        <type name="team" sortOrder="40">
            <label>Our Team</label>
            <resource>page_builder</resource>
        </type>
        
        <type name="testimonial" sortOrder="40">
            <label>Testimonials</label>
            <resource>page_builder</resource>
        </type>

		<type name="other" sortOrder="1000">
			<label>Others</label>
			<resource>page_builder</resource>
		</type>
	</types>
    <sections>
    	<include path="Vnecoms_PageBuilder::vcms_section/default.xml" />
    	<include path="Vnecoms_PageBuilder::vcms_section/feature8.xml" />
    	<include path="Vnecoms_PageBuilder::vcms_section/feature9.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/feature1.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/feature2.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/feature3.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/feature4.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/feature5.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/feature6.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/feature7.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/faq1.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/faq2.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/other-1col.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/other-2cols.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/other-3cols.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/other-4cols.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/welcome1.xml" />
        
        <include path="Vnecoms_PageBuilder::vcms_section/team1.xml" />
        <include path="Vnecoms_PageBuilder::vcms_section/team2.xml" />
        
        <include path="Vnecoms_PageBuilder::vcms_section/testimonial1.xml" />
        
        
        <include path="Vnecoms_PageBuilder::vcms_section/layout-2column-left.xml" />
	</sections>
</config>
