=== Simicart/bianca-nera/Store/app/code/Vnecoms/PageBuilder/etc/vcms_component.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config" type="configDeclaration"/>

    <xs:complexType name="configDeclaration">
        <xs:sequence>
            <xs:element ref="components" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="components">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="field" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueFieldName">
            <xs:annotation>
                <xs:documentation>
                    Attribute id is unique under all widgets
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="field"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:attributeGroup name="fieldAttributeGroup">
        <xs:attribute name="name" type="componentName" use="required" />
    </xs:attributeGroup>

    <xs:element name="field">
        <xs:annotation>
            <xs:documentation>
                Field Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element name="template" type="xs:string" />
                    <xs:element name="edit_template" type="xs:string" />
                    <xs:element name="component" type="xs:string" />
                    <xs:element name="class" type="xs:string" />
                    <xs:element name="block_template" type="xs:string" />
                </xs:choice>
            </xs:sequence>

            <xs:attributeGroup ref="fieldAttributeGroup"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="componentName">
        <xs:annotation>
            <xs:documentation>
                Item id attribute for elements section, widget, field can has only [a-zA-Z0-9/_]. Minimal length 2 symbol. Case sensitive.
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]{1,}" />
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Simicart/bianca-nera/magento/app/code/Vnecoms/PageBuilder/etc/vcms_component.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_PageBulder:etc/vcms_component.xsd">
	<components>
        <field name="h1">
        	<template>Vnecoms_PageBuilder/field/h1</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/h1</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/text</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Text</class>
        	<block_template>Vnecoms_PageBuilder::field/h1.phtml</block_template>
        </field>
        <field name="h2">
        	<template>Vnecoms_PageBuilder/field/h2</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/h2</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/text</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Text</class>
        	<block_template>Vnecoms_PageBuilder::field/h2.phtml</block_template>
        </field>
        <field name="h3">
        	<template>Vnecoms_PageBuilder/field/h3</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/h3</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/text</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Text</class>
        	<block_template>Vnecoms_PageBuilder::field/h3.phtml</block_template>
        </field>
        <field name="h4">
        	<template>Vnecoms_PageBuilder/field/h4</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/h4</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/text</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Text</class>
        	<block_template>Vnecoms_PageBuilder::field/h4.phtml</block_template>
        </field>
        <field name="h5">
        	<template>Vnecoms_PageBuilder/field/h5</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/h5</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/text</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Text</class>
        	<block_template>Vnecoms_PageBuilder::field/h5.phtml</block_template>
        </field>
        <field name="p">
        	<template>Vnecoms_PageBuilder/field/p</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/p</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/html</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Html</class>
        	<block_template>Vnecoms_PageBuilder::field/p.phtml</block_template>
        </field>
        <field name="div">
        	<template>Vnecoms_PageBuilder/field/div</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/div</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/html</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Html</class>
        	<block_template>Vnecoms_PageBuilder::field/div.phtml</block_template>
        </field>
        <field name="code">
        	<template>Vnecoms_PageBuilder/field/div</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/code</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/code</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Html</class>
        	<block_template>Vnecoms_PageBuilder::field/div.phtml</block_template>
        </field>
        <field name="editor">
        	<template>Vnecoms_PageBuilder/field/div</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/editor</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/editor</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Html</class>
        	<block_template>Vnecoms_PageBuilder::field/div.phtml</block_template>
        </field>
        <field name="link">
        	<template>Vnecoms_PageBuilder/field/link</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/link</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/link</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Link</class>
        	<block_template>Vnecoms_PageBuilder::field/link.phtml</block_template>
        </field>
        <field name="icon">
        	<template>Vnecoms_PageBuilder/field/icon</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/icon</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/icon</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Icon</class>
        	<block_template>Vnecoms_PageBuilder::field/icon.phtml</block_template>
        </field>
        <field name="group">
        	<template>Vnecoms_PageBuilder/field/group</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/group</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/group</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Group</class>
        	<block_template>Vnecoms_PageBuilder::field/group.phtml</block_template>
        </field>
        <field name="list">
        	<template>Vnecoms_PageBuilder/field/list</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/list</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/list</component>
        	<class>Vnecoms\PageBuilder\Block\Field\ListBlock</class>
        	<block_template>Vnecoms_PageBuilder::field/list.phtml</block_template>
        </field>
		<field name="img">
        	<template>Vnecoms_PageBuilder/field/img</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/img</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/img</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Img</class>
        	<block_template>Vnecoms_PageBuilder::field/img.phtml</block_template>
        </field>
        <field name="container">
        	<template>Vnecoms_PageBuilder/field/container</template>
        	<edit_template>Vnecoms_PageBuilder/field/edit/container</edit_template>
        	<component>Vnecoms_PageBuilder/js/field/container</component>
        	<class>Vnecoms\PageBuilder\Block\Field\Container</class>
        	<block_template>Vnecoms_PageBuilder::field/container.phtml</block_template>
        </field>
    </components>
</config>
